# Base URL for the PC Scoring Manager, including 'http://'
base_address: http://127.0.0.1:9268

# how long to go between parsing queries, in seconds
parsing_period: 0.1

# Whether or not to use a manual timer to overide the one from the scoring manager
manual_timer: false

# Whether to run a webserver for a timer page
host_timer_webserver: true
webserver_hostip: 0.0.0.0
webserver_port: 9269

# Whether to auto-switch to the next upcoming match
auto_switchover: true
# Amount of time in seconds after a match ends to wait before
# automatically switching labels to the next upcoming match.
switchover_time: 10.0

# Whether to include the phase (e.g. "Seeding") in the match_num_file along
#  with the match number
show_match_phase: true

# Use OBS websockets instead of files.
#  If true, it will make all changes (including text) via websockets. All
#           file-related configs are ignored.
#  If false (or omitted), it will only make changes via text files. All
#           OBS websocket-related configs (and "source" related configs) are ignored.
use_obs_websocket: true

obs_websocket_addr: 127.0.0.1
obs_websocket_port: 4455
obs_websocket_pw: Ben_is_cool

# All file paths will be relative to this path:
rel_file_path: C:\Users\RM BEST\Documents\obs_text

timer_file: timer.txt
match_num_file: match_num.txt

timer_source: TimerText
match_num_source: MatchNumText

fields:
# if you have multiple fields, add multiple sets of params (starting with the dash)
  - red_file:     f1_red.txt
    green_file:   f1_green.txt
    yellow_file:  f1_yellow.txt
    blue_file:    f1_blue.txt
    red_source:    Red
    green_source:  Green
    yellow_source: Yellow
    blue_source:   Blue